-- achievements_skills.lua
-- Skills & Weapon Achievements (English only, Turtle WoW Classic 1.12)

KAMN = KAMN or {}
KAMN.achievements = KAMN.achievements or {}

-- Example: { id = "SKILL_ALCHEMY_75", name = "Apprentice Alchemist", ... }

-- Professions
table.insert(KAMN.achievements, { id = "SKILL_ALCHEMY_75", name = "Apprentice Alchemist", description = "Reach 75 skill points in Alchemy.", type = "skill", skillname = "Alchemy", value = 75, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_BLACKSMITHING_75", name = "Apprentice Blacksmith", description = "Reach 75 skill points in Blacksmithing.", type = "skill", skillname = "Blacksmithing", value = 75, progress = 1, complete = false, category = "Skills", points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_COOKING_75", name = "Campfire Chef", description = "Reach 75 skill points in Cooking.", type = "skill", skillname = "Cooking", value = 75, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_ENCHANTING_75", name = "Runed Beginner", description = "Reach 75 skill points in Enchanting.", type = "skill", skillname = "Enchanting", value = 75, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_ENGINEERING_75", name = "Tinkerer Trainee", description = "Reach 75 skill points in Engineering.", type = "skill", skillname = "Engineering", value = 75, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_FIRSTAID_75", name = "Field Medic", description = "Reach 75 skill points in First Aid.", type = "skill", skillname = "First Aid", value = 75, progress = 1, complete = false, category = "Skills" , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_FISHING_75", name = "Beginner Angler", description = "Reach 75 skill points in Fishing.", type = "skill", skillname = "Fishing", value = 75, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_HERBALISM_75", name = "Herb Handler", description = "Reach 75 skill points in Herbalism.", type = "skill", skillname = "Herbalism", value = 75, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_LEATHERWORKING_75", name = "Hide Handler", description = "Reach 75 skill points in Leatherworking.", type = "skill", skillname = "Leatherworking", value = 75, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_MINING_75", name = "Ore Opener", description = "Reach 75 skill points in Mining.", type = "skill", skillname = "Mining", value = 75, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_SKINNING_75", name = "Skins and Things", description = "Reach 75 skill points in Skinning.", type = "skill", skillname = "Skinning", value = 75, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_TAILORING_75", name = "Thread Learner", description = "Reach 75 skill points in Tailoring.", type = "skill", skillname = "Tailoring", value = 75, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_JEWELCRAFTING_75", name = "Jewelcrafting Learner", description = "Reach 75 skill points in Jewelcrafting.", type = "skill", skillname = "Jewelcrafting", value = 75, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })

-- Weapon Skills
table.insert(KAMN.achievements, { id = "SKILL_UNARMED_50", name = "Barehanded Fighter", description = "Reach 50 skill points in Unarmed.", type = "weapon", skillname = "Unarmed", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_DEFENSE_50", name = "Tough Defender", description = "Reach 50 skill points in Defense.", type = "weapon", skillname = "Defense", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_AXES_50", name = "Axe Novice", description = "Reach 50 skill points in Axes.", type = "weapon", skillname = "Axes", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_BOWS_50", name = "Bow Trainee", description = "Reach 50 skill points in Bows.", type = "weapon", skillname = "Bows", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_CROSSBOWS_50", name = "Crossbow Initiate", description = "Reach 50 skill points in Crossbows.", type = "weapon", skillname = "Crossbows", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_DAGGERS_50", name = "Dagger Beginner", description = "Reach 50 skill points in Daggers.", type = "weapon", skillname = "Daggers", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_GUNS_50", name = "Gun Handler", description = "Reach 50 skill points in Guns.", type = "weapon", skillname = "Guns", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_MACES_50", name = "Mace Trainee", description = "Reach 50 skill points in Maces.", type = "weapon", skillname = "Maces", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_POLEARMS_50", name = "Polearm Apprentice", description = "Reach 50 skill points in Polearms.", type = "weapon", skillname = "Polearms", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_STAVES_50", name = "Staff Student", description = "Reach 50 skill points in Staves.", type = "weapon", skillname = "Staves", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_SWORDS_50", name = "Sword Beginner", description = "Reach 50 skill points in Swords.", type = "weapon", skillname = "Swords", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_THROWN_50", name = "Thrower Trainee", description = "Reach 50 skill points in Thrown.", type = "weapon", skillname = "Thrown", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_TWO_HANDED_AXES_50", name = "Two-Axe Student", description = "Reach 50 skill points in Two-Handed Axes.", type = "weapon", skillname = "Two-Handed Axes", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_TWO_HANDED_MACES_50", name = "Heavy Mace Beginner", description = "Reach 50 skill points in Two-Handed Maces.", type = "weapon", skillname = "Two-Handed Maces", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_TWO_HANDED_SWORDS_50", name = "Blade Mastery Novice", description = "Reach 50 skill points in Two-Handed Swords.", type = "weapon", skillname = "Two-Handed Swords", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_WANDS_50", name = "Wand Wielder", description = "Reach 50 skill points in Wands.", type = "weapon", skillname = "Wands", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
table.insert(KAMN.achievements, { id = "SKILL_FIST_WEAPONS_50", name = "Fist Fighter", description = "Reach 50 skill points in Fist Weapons.", type = "weapon", skillname = "Fist Weapons", value = 50, progress = 1, complete = false, category = "Skills" , points = 5 , requiredFor = {} })
